"""Static UI label localization for the offline report.

No gettext/Babel; a fixed dictionary is enough for the presentation layer.
"""

from __future__ import annotations

SUPPORTED_LOCALES = {"zh-CN", "en"}
DEFAULT_LOCALE = "zh-CN"

TEXT = {
    "zh-CN": {
        "investment_report": "投资分析报告",
        "trade_date": "分析日期",
        "company": "公司",
        "industry": "行业",
        "status": "运行状态",
        "current_price": "当前价格",
        "price_as_of": "截至",
        "target_price": "目标价格",
        "stop_loss": "止损价格",
        "position": "建议仓位",
        "confidence": "置信度",
        "risk_level": "风险等级",
        "time_horizon": "投资周期",
        "executive_summary": "投资摘要",
        "investment_thesis": "核心投资逻辑",
        "composite_score": "四维分析评分",
        "financial_summary": "核心财务指标",
        "price_chart": "价格与技术走势",
        "bull_case": "多头观点",
        "bear_case": "空头观点",
        "research_manager_conclusion": "研究经理结论",
        "risk_assessment": "三方风险评估",
        "risk_radar_note": "分数越高代表感知风险越高",
        "financial_history": "历史财务趋势",
        "detailed_analysis": "详细分析",
        "technical_analysis": "技术面分析",
        "fundamentals_analysis": "基本面分析",
        "news_analysis": "新闻分析",
        "sentiment_analysis": "市场情绪分析",
        "event_timeline": "关键事件时间线",
        "risk_register": "风险清单",
        "risk_summary": "风险摘要",
        "data_quality": "数据质量与限制",
        "unavailable": "暂无可靠数据",
        "not_rated": "暂无评级",
        "disclaimer": (
            "本报告由 AI 自动生成，仅供研究和教育用途，不构成投资建议。"
            "请独立核实所有数据并自行承担投资决策风险。"
        ),
        "raw_portfolio_decision": "原始投资决策文本",
        "metric": "指标",
        "value": "数值",
        "unit": "单位",
        "period": "期间",
        "missing_sections": "缺失模块",
        "unparsed_sources": "未解析数据源",
        "notes": "备注",
        "rating": "评级",
        "impact": "影响",
        "importance": "重要程度",
        "reason": "原因",
        "source": "来源",
        "link": "链接",
        "detail": "详情",
        "date": "日期",
        "event": "事件",
        "severity": "严重程度",
        "horizon": "时间跨度",
        "evidence": "依据",
        "argument": "论点",
        "strength": "强度",
        "risk_score": "风险评分",
        "summary": "总结",
        "up_to": "至多",
        "at_least": "至少",
        # P0 new labels
        "risk_reward": "风险收益比",
        "trading_plan": "执行计划",
        "holding_action": "当前持仓策略",
        "entry_condition": "入场条件",
        "exit_condition": "离场条件",
        "monitoring_events": "关注事件",
        "technical_snapshot": "技术指标快照",
        "trend": "趋势",
        "support": "支撑",
        "resistance": "阻力",
        "rsi_label": "RSI",
        "macd_label": "MACD",
        "macd_signal_label": "信号线",
        "macd_histogram_label": "柱状",
        "bollinger_label": "布林带",
        "kdj_label": "KDJ",
        "debate_resolution": "研究经理裁决",
        "core_disagreement": "核心分歧",
        "key_bull_points": "关键多头要点",
        "key_bear_points": "关键空头要点",
        "decisive_factors": "决定性因素",
        "final_reason": "最终理由",
        "vs_prior_period": "较上期",
        "financial_quality": "财务质量评估",
        "quality_warnings": "质量警示",
        # P1 new labels
        "analyst_consensus": "机构一致预期",
        "target_low": "目标价 (低)",
        "target_mean": "目标价 (均值)",
        "target_median": "目标价 (中位)",
        "target_high": "目标价 (高)",
        "implied_upside": "隐含涨跌幅",
        "eps_estimate": "EPS 预测",
        "revenue_estimate": "营收预测",
        "analyst_count": "分析师数",
        "recommendation_summary": "评级分布",
        "catalyst_watchlist": "催化剂观察清单",
        "scheduled": "已排期",
        "watching": "观察中",
        "trigger": "触发条件",
        "invalidation": "失效条件",
        "follow_up": "跟进计划",
        "higher_risk_note": "分数越高代表感知风险越高",
        "model_probability": "模型概率估计",
        "downside_impact": "下行影响估计",
        "expected_loss": "预期损失估计",
        "short_term": "短期",
        "medium_term": "中期",
        "long_term": "长期",
        "unclassified": "未分类",
        "insider_kind": "内幕交易",
        # P2
        "eps_revisions_title": "EPS 预测修正趋势",
        "earnings_realization": "历史业绩兑现",
        "report_date": "报告日期",
        "eps_estimate_v": "EPS 预测值",
        "reported_eps_v": "实际 EPS",
        "surprise": "超预期幅度",
        "valuation_context": "估值上下文",
        "market_multiples": "市场估值倍数",
        "pe_ttm": "市盈率 (TTM)",
        "forward_pe_v": "远期市盈率",
        "pb_v": "市净率",
        "peg_v": "PEG",
        "pe_compression": "PE 压缩",
        "analyst_consensus_v": "机构一致预期",
        "pm_target_note": "机构目标价与投资组合经理决策相互独立",
        "market_risk_stats": "市场风险统计",
        "return_5d": "5日回报",
        "return_20d": "20日回报",
        "realized_vol_20d": "年化波动率 (20日)",
        "max_drawdown_60": "最大回撤 (≤60日)",
        "atr14_pct_v": "ATR14 / 价格",
        "volume_ratio_20d_v": "量比 (20日)",
        "ownership_sentiment": "持仓与情绪证据",
        "ownership_summary": "持仓概况",
        "insiders_pct_v": "内部人持股",
        "institutions_pct_v": "机构持股",
        "institutions_float_v": "机构流通股占比",
        "institutions_count_v": "机构数量",
        "institutional_holders_v": "机构持仓 Top 5",
        "mutual_fund_holders_v": "共同基金持仓 Top 5",
        "grounded_signals": "结构化情绪信号",
        "ownership_disclaimer": "持仓数据为报告期上下文，不自动隐含买卖方向判断。",
        "provenance": "数据来源",
        "retrieved_at": "获取时间",
        "data_as_of": "数据截至",
        "structured_keys": "结构化字段",
        "truncated_v": "截断",
        "conflicts": "数据冲突",
        "selected": "选定",
        # P2 table-level headers
        "current_estimate": "当前预测",
        "days_7_ago": "7日前",
        "days_30_ago": "30日前",
        "days_60_ago": "60日前",
        "days_90_ago": "90日前",
        "up_revisions_7d": "7日上调",
        "down_revisions_7d": "7日下调",
        "up_revisions_30d": "30日上调",
        "down_revisions_30d": "30日下调",
        "target_mean_v": "目标价 (均值)",
        "target_median_v": "目标价 (中位)",
        "upside_mean_v": "上行空间 (均值)",
        "eps_growth_cy": "EPS 增长 (本财年)",
        "eps_growth_ny": "EPS 增长 (下一财年)",
        "holder_v": "持有人",
        "shares_v": "持股数",
        "pct_out_v": "占比",
        "direction_v": "方向",
        "strength_v": "强度",
        "reasoning_v": "理由",
        "evidence_v": "证据",
        "tool": "工具",
        "ok": "状态",
        # P1: KPI display labels (zh-CN)
        "kpi_market_cap": "总市值",
        "kpi_pe_ttm": "市盈率 (TTM)",
        "kpi_forward_pe": "远期市盈率",
        "kpi_price_to_book": "市净率",
        "kpi_revenue_ttm": "营收 (TTM)",
        "kpi_net_income": "净利润",
        "kpi_profit_margin": "净利润率",
        "kpi_return_on_equity": "净资产收益率",
        "kpi_total_debt": "总负债",
        "kpi_free_cash_flow": "自由现金流",
        "kpi_current_ratio": "流动比率",
        "kpi_operating_margin": "营业利润率",
        # P1: Technical snapshot labels
        "trend_bullish": "看涨",
        "trend_bearish": "看跌",
        "trend_mixed": "震荡",
        "trend_unknown": "未知",
        # P1: Analyst consensus labels
        "target_low_v": "目标价 (低)",
        "target_mean_v": "目标价 (均值)",
        "target_median_v": "目标价 (中位)",
        "target_high_v": "目标价 (高)",
        "vendor_current": "当前价",
        "upside_mean_v": "上行空间 (均值)",
        "upside_median_v": "上行空间 (中位)",
        "strong_buy": "强烈买入",
        "strong_sell": "强烈卖出",
        "buy": "买入",
        "hold": "持有",
        "sell": "卖出",
        "period_current_month": "本月",
        "period_current_quarter": "本季度",
        "change_30d": "30日变化",
        "net_revisions": "净修正",
        "evidence_20d_return": "20日收益率",
        "evidence_drawdown_60": "60交易日最大回撤",
        "evidence_target_mean": "机构一致预期均值目标",
        "evidence_eps_revision": "EPS预测修正",
        "evidence_earnings_surprise": "业绩意外幅度",
        "evidence_ownership_summary": "持仓结构摘要",
        "evidence_holder": "机构持有人",
        "period_next_quarter": "下季度",
        "period_current_year": "本财年",
        "period_next_year": "下一财年",
        "growth_pct": "增长",
        "avg": "均值",
        "low": "低",
        "high": "高",
        # P1: Supporting evidence labels
        "supporting_financial_metrics": "补充财务指标",
        "supporting_charts": "补充图表",
        "risk_radar_title": "风险维度对比",
        # P2: Decision Evidence Audit
        "decision_evidence_audit": "决策证据审计",
        "supporting_current_decision": "支持当前结论",
        "conflicting_evidence": "反向证据",
        "context_evidence": "背景信息",
        "audit_not_second_decision": "本模块仅审计现有结论的证据一致性，不构成第二次投资决策。",
        "evidence_id": "证据 ID",
        # P2: Research Diagnostics
        "research_diagnostics": "研究诊断",
        "estimate_revision_diagnostic": "预期修正",
        "earnings_realization": "历史业绩兑现",
        "valuation_consensus_diagnostic": "估值与一致预期",
        "market_risk_stats": "市场风险",
        "ownership_structure": "持仓结构",
        "sample_size": "样本数量",
        "beat_rate": "超预期率",
        "mean_surprise": "平均超预期",
        "latest_surprise": "最近一次超预期",
        "target_dispersion": "目标价离散度",
        "top_holder": "最大机构持有人",
        "top5_concentration": "前5集中度",
        "retained_holder_count": "保留持有人数",
        "raw_details": "原始数据详情",
        # P2: Data Reliability Summary
        "data_reliability_summary": "数据可靠性摘要",
        "source_count": "数据源数量",
        "failed_source_count": "失败数据源",
        "truncated_source_count": "截断数据源",
        "conflict_count": "数据冲突数",
        "missing_section_count": "缺失模块数",
        "stale_market_data": "市场数据过期",
        "yes": "是",
        "no": "否",
        # P2: Direction / relation labels
        "dir_positive": "正面",
        "dir_negative": "负面",
        "dir_neutral": "中性",
        "dir_mixed": "混合",
        "dir_unknown": "未知",
        "dir_rising": "上调",
        "dir_falling": "下调",
        "dir_flat": "持平",
        "rel_support": "支持",
        "rel_conflict": "反向",
        "rel_context": "背景",
    },
    "en": {
    },
    "en": {
        "investment_report": "Investment Analysis Report",
        "trade_date": "Trade date",
        "company": "Company",
        "industry": "Industry",
        "status": "Status",
        "current_price": "Current Price",
        "price_as_of": "as of",
        "target_price": "Target Price",
        "stop_loss": "Stop Loss",
        "position": "Recommended Position",
        "confidence": "Confidence",
        "risk_level": "Risk Level",
        "time_horizon": "Time Horizon",
        "executive_summary": "Executive Summary",
        "investment_thesis": "Investment Thesis",
        "composite_score": "Four-Dimension Analysis Scores",
        "financial_summary": "Key Financial Metrics",
        "price_chart": "Price & Technical Trend",
        "bull_case": "Bull Case",
        "bear_case": "Bear Case",
        "research_manager_conclusion": "Research Manager Conclusion",
        "risk_assessment": "Three-way Risk Assessment",
        "risk_radar_note": "Higher score = higher perceived risk",
        "financial_history": "Historical Financials",
        "detailed_analysis": "Detailed Analysis",
        "technical_analysis": "Technical Analysis",
        "fundamentals_analysis": "Fundamentals Analysis",
        "news_analysis": "News Analysis",
        "sentiment_analysis": "Sentiment Analysis",
        "event_timeline": "Key Event Timeline",
        "risk_register": "Risk Register",
        "risk_summary": "Risk Summary",
        "data_quality": "Data quality and limitations",
        "unavailable": "Unavailable",
        "not_rated": "Not rated",
        "disclaimer": (
            "This AI-generated report is for research and educational purposes "
            "only and does not constitute investment advice. Verify all data "
            "independently and make investment decisions at your own risk."
        ),
        "raw_portfolio_decision": "Raw portfolio decision",
        "metric": "Metric",
        "value": "Value",
        "unit": "Unit",
        "period": "Period",
        "missing_sections": "Missing sections",
        "unparsed_sources": "Unparsed sources",
        "notes": "Notes",
        "rating": "Rating",
        "impact": "Impact",
        "importance": "Importance",
        "reason": "Reason",
        "source": "Source",
        "link": "Link",
        "detail": "Detail",
        "date": "Date",
        "event": "Event",
        "severity": "Severity",
        "horizon": "Horizon",
        "evidence": "Evidence",
        "argument": "Argument",
        "strength": "Strength",
        "risk_score": "Risk score",
        "summary": "Summary",
        "up_to": "Up to",
        "at_least": "At least",
        # P0 new labels
        "risk_reward": "Risk/Reward",
        "trading_plan": "Trading Plan",
        "holding_action": "Holding Action",
        "entry_condition": "Entry Condition",
        "exit_condition": "Exit Condition",
        "monitoring_events": "Monitoring Events",
        "technical_snapshot": "Technical Snapshot",
        "trend": "Trend",
        "support": "Support",
        "resistance": "Resistance",
        "rsi_label": "RSI",
        "macd_label": "MACD",
        "macd_signal_label": "Signal",
        "macd_histogram_label": "Histogram",
        "bollinger_label": "Bollinger",
        "kdj_label": "KDJ",
        "debate_resolution": "Research Manager Verdict",
        "core_disagreement": "Core Disagreement",
        "key_bull_points": "Key Bull Points",
        "key_bear_points": "Key Bear Points",
        "decisive_factors": "Decisive Factors",
        "final_reason": "Final Reason",
        "vs_prior_period": "vs prior period",
        "financial_quality": "Financial Quality",
        "quality_warnings": "Quality Warnings",
        # P1 new labels
        "analyst_consensus": "Analyst Consensus",
        "target_low": "Target (Low)",
        "target_mean": "Target (Mean)",
        "target_median": "Target (Median)",
        "target_high": "Target (High)",
        "implied_upside": "Implied Upside",
        "eps_estimate": "EPS Estimate",
        "revenue_estimate": "Revenue Estimate",
        "analyst_count": "Analysts",
        "recommendation_summary": "Recommendations",
        "catalyst_watchlist": "Catalyst Watchlist",
        "scheduled": "Scheduled",
        "watching": "Watching",
        "trigger": "Trigger",
        "invalidation": "Invalidation",
        "follow_up": "Follow-up",
        "higher_risk_note": "Higher score = higher perceived risk",
        "model_probability": "Model probability estimate",
        "downside_impact": "Downside impact estimate",
        "expected_loss": "Expected loss estimate",
        "short_term": "Short-term",
        "medium_term": "Medium-term",
        "long_term": "Long-term",
        "unclassified": "Unclassified",
        "insider_kind": "Insider",
        # P2
        "eps_revisions_title": "EPS Estimate Revision Trend",
        "earnings_realization": "Earnings Realization",
        "report_date": "Report Date",
        "eps_estimate_v": "EPS Estimate",
        "reported_eps_v": "Reported EPS",
        "surprise": "Surprise",
        "valuation_context": "Valuation Context",
        "market_multiples": "Market Multiples",
        "pe_ttm": "P/E (TTM)",
        "forward_pe_v": "Forward P/E",
        "pb_v": "P/B",
        "peg_v": "PEG",
        "pe_compression": "PE Compression",
        "analyst_consensus_v": "Analyst Consensus",
        "pm_target_note": "Analyst targets are independent from the Portfolio Manager decision.",
        "market_risk_stats": "Market Risk Statistics",
        "return_5d": "5-Day Return",
        "return_20d": "20-Day Return",
        "realized_vol_20d": "Realized Vol (20d, ann.)",
        "max_drawdown_60": "Max Drawdown (≤60 sessions)",
        "atr14_pct_v": "ATR14 / Price",
        "volume_ratio_20d_v": "Volume Ratio (20d)",
        "ownership_sentiment": "Ownership & Sentiment Evidence",
        "ownership_summary": "Ownership Summary",
        "insiders_pct_v": "Insiders %",
        "institutions_pct_v": "Institutions %",
        "institutions_float_v": "Inst. Float %",
        "institutions_count_v": "Institution Count",
        "institutional_holders_v": "Top 5 Institutional Holders",
        "mutual_fund_holders_v": "Top 5 Mutual Fund Holders",
        "grounded_signals": "Grounded Sentiment Signals",
        "ownership_disclaimer": "Ownership data is reported context and does not automatically imply buying or selling direction.",
        "provenance": "Data Provenance",
        "retrieved_at": "Retrieved",
        "data_as_of": "Data As Of",
        "structured_keys": "Structured Keys",
        "truncated_v": "Truncated",
        "conflicts": "Data Conflicts",
        "selected": "Selected",
        # P2 table-level headers
        "current_estimate": "Current Est.",
        "days_7_ago": "7d Ago",
        "days_30_ago": "30d Ago",
        "days_60_ago": "60d Ago",
        "days_90_ago": "90d Ago",
        "up_revisions_7d": "Up 7d",
        "down_revisions_7d": "Down 7d",
        "up_revisions_30d": "Up 30d",
        "down_revisions_30d": "Down 30d",
        "target_mean_v": "Target (Mean)",
        "target_median_v": "Target (Median)",
        "upside_mean_v": "Upside (Mean)",
        "eps_growth_cy": "EPS Growth (CY)",
        "eps_growth_ny": "EPS Growth (NY)",
        "holder_v": "Holder",
        "shares_v": "Shares",
        "pct_out_v": "% Out",
        "direction_v": "Direction",
        "strength_v": "Strength",
        "reasoning_v": "Reasoning",
        "evidence_v": "Evidence",
        "tool": "Tool",
        "ok": "OK",
        # P1: KPI display labels
        "kpi_market_cap": "Market Cap",
        "kpi_pe_ttm": "P/E (TTM)",
        "kpi_forward_pe": "Forward P/E",
        "kpi_price_to_book": "P/B",
        "kpi_revenue_ttm": "Revenue (TTM)",
        "kpi_net_income": "Net Income",
        "kpi_profit_margin": "Net Margin",
        "kpi_return_on_equity": "ROE",
        "kpi_total_debt": "Total Debt",
        "kpi_free_cash_flow": "Free Cash Flow",
        "kpi_current_ratio": "Current Ratio",
        "kpi_operating_margin": "Operating Margin",
        # P1: Technical snapshot labels
        "trend_bullish": "Bullish",
        "trend_bearish": "Bearish",
        "trend_mixed": "Mixed",
        "trend_unknown": "Unknown",
        # P1: Analyst consensus labels
        "target_low_v": "Target (Low)",
        "target_mean_v": "Target (Mean)",
        "target_median_v": "Target (Median)",
        "target_high_v": "Target (High)",
        "vendor_current": "Current",
        "upside_mean_v": "Upside (Mean)",
        "upside_median_v": "Upside (Median)",
        "strong_buy": "Strong Buy",
        "strong_sell": "Strong Sell",
        "buy": "Buy",
        "hold": "Hold",
        "sell": "Sell",
        "period_current_month": "Current Month",
        "period_current_quarter": "Current Qtr",
        "change_30d": "30-Day Change",
        "net_revisions": "Net Revisions",
        "evidence_20d_return": "20-Day Return",
        "evidence_drawdown_60": "60-Session Max Drawdown",
        "evidence_target_mean": "Analyst Consensus Mean Target",
        "evidence_eps_revision": "EPS Estimate Revision",
        "evidence_earnings_surprise": "Earnings Surprise",
        "evidence_ownership_summary": "Ownership Summary",
        "evidence_holder": "Institutional Holder",
        "period_next_quarter": "Next Qtr",
        "period_current_year": "Current Year",
        "period_next_year": "Next Year",
        "growth_pct": "Growth",
        "avg": "Avg",
        "low": "Low",
        "high": "High",
        # P1: Supporting evidence labels
        "supporting_financial_metrics": "Supporting Financial Metrics",
        "supporting_charts": "Supporting Charts",
        "risk_radar_title": "Risk Dimension Comparison",
        # P2: Decision Evidence Audit
        "decision_evidence_audit": "Decision Evidence Audit",
        "supporting_current_decision": "Supports Current Conclusion",
        "conflicting_evidence": "Conflicting Evidence",
        "context_evidence": "Background Context",
        "audit_not_second_decision": "This block audits evidence consistency with the existing conclusion only; it is not a second investment decision.",
        "evidence_id": "Evidence ID",
        # P2: Research Diagnostics
        "research_diagnostics": "Research Diagnostics",
        "estimate_revision_diagnostic": "Estimate Revision",
        "earnings_realization": "Earnings Realization",
        "valuation_consensus_diagnostic": "Valuation & Consensus",
        "market_risk_stats": "Market Risk",
        "ownership_structure": "Ownership Structure",
        "sample_size": "Sample Size",
        "beat_rate": "Beat Rate",
        "mean_surprise": "Mean Surprise",
        "latest_surprise": "Latest Surprise",
        "target_dispersion": "Target Dispersion",
        "top_holder": "Top Holder",
        "top5_concentration": "Top 5 Concentration",
        "retained_holder_count": "Retained Holders",
        "raw_details": "Raw Details",
        # P2: Data Reliability Summary
        "data_reliability_summary": "Data Reliability Summary",
        "source_count": "Sources",
        "failed_source_count": "Failed Sources",
        "truncated_source_count": "Truncated Sources",
        "conflict_count": "Conflicts",
        "missing_section_count": "Missing Sections",
        "stale_market_data": "Stale Market Data",
        "yes": "Yes",
        "no": "No",
        # P2: Direction / relation labels
        "dir_positive": "Positive",
        "dir_negative": "Negative",
        "dir_neutral": "Neutral",
        "dir_mixed": "Mixed",
        "dir_unknown": "Unknown",
        "dir_rising": "Rising",
        "dir_falling": "Falling",
        "dir_flat": "Flat",
        "rel_support": "Support",
        "rel_conflict": "Conflict",
        "rel_context": "Context",
    },
}


def text(key: str, locale: str = DEFAULT_LOCALE) -> str:
    """Return the static label for ``key`` in ``locale`` (fallback zh-CN)."""
    if locale not in SUPPORTED_LOCALES:
        locale = DEFAULT_LOCALE
    return TEXT.get(locale, TEXT[DEFAULT_LOCALE]).get(key, key)
